### ISSUE TITLE
IP proxy.

### ISSUE THREAD

**Issue by gaojiuli** [gaojiuli/gain#17]
Support IP proxy.

**Comment by xxllp** [comment]
文档太少了，案例也是

**Comment by gaojiuli** [comment]
文档与案例会在发布1.0前补充完整, 现阶段主要是功能的完善和bug的修复.

**Comment by Jie-OY** [comment]
Using a existing IP Proxy Crawler repo or , planning to create a repo doing that by ourselves where Gain can get IP Proxy from.

**Comment by gaojiuli** [comment]
@Jie-OY Use  exist IP Proxy tool.
