### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by Jie-OY** [gaojiuli/gain#20]
1. Spider class add cookies field cause some websites need login

2. In parser.py file,there is `await item.save()`, a function used to store information mostly in local file(user can override the function). As far as i'm concerned, code like 
```
    async def save(self):
        with open('scrapinghub.txt', 'a+') as f:
            f.writelines(str(self.results) + '\n')

```
is blocking as local filesystem access is blocking.Therefore,the event loop(Thread) is blocking.
Especially when we select a MB  size file and want to store in local file, it would slow the whole application.

So, It's that possible use **aiofile**(File support for asyncio,https://github.com/Tinche/aiofiles) or use loop.run_in_executor makes save funciton run in another thread when the file is large?

**Comment by gaojiuli** [comment]
1. Putting the cookies into headers is better.
2.   I agree with you, `loop.run_in_executor` is better

**Comment by Jie-OY** [comment]
Get it... Don't need  to add cookies field

**Comment by georgedorn** [comment]
An example of getting cookies from a login and setting them in the header would be helpful.  Should I just use the requests library to do the login, then extract the appropriate cookie and set it according?

**Comment by gaojiuli** [comment]
@georgedorn Coping cookies from browser is the right way.
