### ISSUE TITLE
RuntimeError: uvloop does not support Windows at the moment.

### ISSUE THREAD

**Issue by sumarsky** [gaojiuli/gain#6]
Add requirement (not windows client)
```
Collecting gain
  Downloading gain-0.1.1.tar.gz
Collecting uvloop (from gain)
  Downloading uvloop-0.8.0.tar.gz (1.7MB)
    100% |################################| 1.7MB 534kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\idi\AppData\Local\Temp\pip-build-gjya289j\uvloop\setup.py", line 11, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment
```

**Comment by gaojiuli** [comment]
This problem has been solved, but we hadn't released a version on pypi.python.org right now.
You could try to install the dev version with command: 

`pip install git+https://github.com/gaojiuli/gain/`
Or 
`pip install gain==0.1.2` (The newest version right now.)

Thanks for your feedback.

**Comment by adonge** [comment]
I use Windows and I install gain success just now.

**Comment by sumarsky** [comment]
Yeah, this works swell.
`pip install git+https://github.com/gaojiuli/gain/`
